#!/usr/local/bin/perl -T
use strict;
use warnings;

my @npg_libs;
BEGIN {
  my $libs_string = $ENV{'NPG_PERL5LIB'};
  if ($libs_string) {
    my @libs = split /:/smx, $libs_string;
    foreach my $l (@libs) {
      my ($dtl) = $l =~ /([\w\/\.\-]+)/smxia;
      #'a' modifiler for ascii only interpretation of \w
      if ($dtl) {push @npg_libs, $dtl;}
    }
  }
}

use lib @npg_libs;
use npg_qc::controller;
use npg_qc::util;

our $VERSION = '0';

npg_qc::controller->handler(npg_qc::util->new());

0;
