#!/usr/local/bin/perl -T

my @npg_libs;
BEGIN {
  my $libs_string = $ENV{'NPG_PERL5LIB'};
  if ($libs_string) {
    my @libs = split /:/smx, $libs_string;
    foreach my $l (@libs) {
      my ($dtl) = $l =~ /([a-z0-9\/\._\-]+)/i;
      if ($dtl) {push @npg_libs, $dtl;}
    }
  }
}

use strict;
use lib @npg_libs;
use warnings;
use npg_qc::controller;
use npg_qc::util;

our $VERSION = '0';

npg_qc::controller->handler(npg_qc::util->new());

0;
